# Generated by Django 5.1.6 on 2026-03-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin_bin', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИИН/БИН')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('entity_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('cooperative', 'С/х кооператив (СПК)')], max_length=20, verbose_name='Тип')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('district', models.CharField(max_length=200, verbose_name='Район')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bank_account', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Банк')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('block_reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('block_until', models.DateField(blank=True, null=True, verbose_name='Блокировка до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Направление субсидирования',
                'verbose_name_plural': 'Направления субсидирования',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('checking', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отказ'), ('waiting_list', 'Лист ожидания'), ('partially_paid', 'Частично выплачена'), ('paid', 'Выплачена')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Норматив')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Причитающаяся сумма')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата подачи')),
                ('region', models.CharField(db_index=True, max_length=200, verbose_name='Область')),
                ('district', models.CharField(max_length=200, verbose_name='Район')),
                ('akimat', models.CharField(blank=True, max_length=500, verbose_name='Акимат')),
                ('animals_data', models.JSONField(blank=True, default=list, verbose_name='Данные о животных')),
                ('esf_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ЭСФ')),
                ('esf_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма ЭСФ')),
                ('counterparty_bin', models.CharField(blank=True, max_length=12, verbose_name='БИН продавца')),
                ('counterparty_name', models.CharField(blank=True, max_length=500, verbose_name='Продавец')),
                ('land_cadastral', models.CharField(blank=True, max_length=50, verbose_name='Кадастровый номер')),
                ('spk_name', models.CharField(blank=True, max_length=500, verbose_name='Название СПК')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scoring.applicant')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('contract', 'Договор купли-продажи'), ('esf', 'ЭСФ'), ('customs_declaration', 'Таможенная декларация'), ('quarantine_act', 'Акт карантинирования'), ('commission_conclusion', 'Заключение спецкомиссии'), ('spk_membership', 'Членство в СПК'), ('payment_confirmation', 'Подтверждение оплаты'), ('veterinary_certificate', 'Ветеринарный сертификат'), ('pedigree_certificate', 'Племенное свидетельство'), ('weighing_act', 'Акт взвешивания'), ('bonitation_act', 'Акт бонитировки'), ('other', 'Прочее')], max_length=30, verbose_name='Тип')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scoring.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Одобрено'), ('rejected', 'Отказ'), ('review', 'Доп. проверка'), ('partially_approved', 'Частично одобрено')], max_length=20, verbose_name='Решение')),
                ('reason', models.TextField(verbose_name='Обоснование')),
                ('rejection_grounds', models.JSONField(blank=True, default=list, verbose_name='Основания отказа')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Одобренная сумма')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='scoring.application')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_decisions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='HardFilterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giss_registered', models.BooleanField(default=False, verbose_name='ГИСС')),
                ('has_eds', models.BooleanField(default=False, verbose_name='ЭЦП')),
                ('ias_rszh_registered', models.BooleanField(default=False, verbose_name='ИАС РСЖ')),
                ('has_agricultural_land', models.BooleanField(default=False, verbose_name='Земля ЕГКН')),
                ('is_iszh_registered', models.BooleanField(default=False, verbose_name='ИС ИСЖ')),
                ('ibspr_registered', models.BooleanField(default=False, verbose_name='ИБСПР')),
                ('esf_confirmed', models.BooleanField(default=False, verbose_name='ЭСФ')),
                ('no_unfulfilled_obligations', models.BooleanField(default=False, verbose_name='Обязательства')),
                ('no_block', models.BooleanField(default=False, verbose_name='Нет блокировки')),
                ('animals_age_valid', models.BooleanField(default=False, verbose_name='Возраст')),
                ('animals_not_subsidized', models.BooleanField(default=False, verbose_name='Не субсидировались')),
                ('all_passed', models.BooleanField(default=False, verbose_name='Все пройдены')),
                ('failed_reasons', models.JSONField(default=list, verbose_name='Причины отказа')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('raw_responses', models.JSONField(default=dict, verbose_name='Сырые ответы')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hard_filter_result', to='scoring.application')),
            ],
            options={
                'verbose_name': 'Результат Hard Filters',
                'verbose_name_plural': 'Результаты Hard Filters',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Балл')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Позиция в рейтинге')),
                ('recommendation', models.CharField(choices=[('approve', 'Одобрить'), ('review', 'На усмотрение'), ('reject', 'Отклонить')], max_length=10, verbose_name='Рекомендация')),
                ('recommendation_reason', models.TextField(verbose_name='Обоснование')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='1.0', max_length=20, verbose_name='Версия модели')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='scoring.application')),
            ],
            options={
                'verbose_name': 'Скоринг',
                'verbose_name_plural': 'Скоринг',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_code', models.CharField(max_length=30, verbose_name='Код фактора')),
                ('factor_name', models.CharField(max_length=200, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Значение')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимум')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Вес')),
                ('weighted_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Взвешенное')),
                ('explanation', models.TextField(verbose_name='Объяснение')),
                ('data_source', models.CharField(max_length=30, verbose_name='Источник')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='scoring.score')),
            ],
            options={
                'verbose_name': 'Фактор скоринга',
                'verbose_name_plural': 'Факторы скоринга',
                'ordering': ['-weighted_value'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(verbose_name='Номер формы')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Норматив (тг)')),
                ('origin', models.CharField(choices=[('domestic', 'Отечественный'), ('cis', 'Импорт СНГ'), ('import', 'Импорт дальнее зарубежье'), ('na', 'Не применимо')], default='na', max_length=20, verbose_name='Происхождение')),
                ('min_age_months', models.IntegerField(blank=True, null=True, verbose_name='Мин. возраст (мес.)')),
                ('max_age_months', models.IntegerField(blank=True, null=True, verbose_name='Макс. возраст (мес.)')),
                ('min_herd_size', models.IntegerField(blank=True, null=True, verbose_name='Мин. поголовье')),
                ('requires_commission', models.BooleanField(default=False, verbose_name='Требует заключения комиссии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='scoring.subsidydirection')),
            ],
            options={
                'verbose_name': 'Вид субсидии',
                'verbose_name_plural': 'Виды субсидий',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='subsidy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scoring.subsidytype'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Заявитель'), ('mio_specialist', 'Специалист МИО'), ('commission_member', 'Член комиссии'), ('mio_head', 'Руководитель МИО'), ('admin', 'Администратор'), ('auditor', 'Аудитор')], default='applicant', max_length=30, verbose_name='Роль')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Область')),
                ('district', models.CharField(blank=True, max_length=200, verbose_name='Район')),
                ('organization', models.CharField(blank=True, max_length=500, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='План')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Факт')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='scoring.subsidydirection')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'unique_together': {('year', 'region', 'direction')},
            },
        ),
    ]
