# Generated by Django 5.1.6 on 2026-03-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('submitted', 'Заявка принята'), ('hard_filter_fail', 'Проверки не пройдены'), ('scored', 'Скоринг завершён'), ('approved', 'Заявка одобрена'), ('rejected', 'Заявка отклонена'), ('waiting_list', 'Лист ожидания'), ('payment_initiated', 'Платёж инициирован'), ('paid', 'Выплата произведена'), ('review', 'Доп. проверка')], max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scoring.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('initiated', 'Инициирован'), ('sent_to_treasury', 'Отправлен в Казначейство'), ('processing', 'В обработке'), ('completed', 'Выплачен'), ('failed', 'Ошибка')], default='initiated', max_length=20, verbose_name='Статус')),
                ('treasury_ref', models.CharField(blank=True, max_length=50, verbose_name='Номер Казначейства')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выплачен')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='scoring.application')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
