# Generated by Django 5.1.6 on 2026-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_notification_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Банковский счёт'),
        ),
        migrations.AddField(
            model_name='application',
            name='ecp_signed',
            field=models.BooleanField(default=False, verbose_name='Подписано ЭЦП'),
        ),
        migrations.AddField(
            model_name='application',
            name='ecp_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписи ЭЦП'),
        ),
        migrations.AddField(
            model_name='application',
            name='invoices_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Данные о ЭСФ'),
        ),
        migrations.AddField(
            model_name='application',
            name='plots_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Данные о земельных участках'),
        ),
    ]
