# Generated by Django 5.1.6 on 2026-03-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_application_bank_account_application_ecp_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iin_bin',
            field=models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ИИН/БИН'),
        ),
    ]
