# Generated by Django 5.1.6 on 2026-03-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_userprofile_iin_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfilterresult',
            name='application_period_valid',
            field=models.BooleanField(default=False, verbose_name='Срок подачи'),
        ),
        migrations.AddField(
            model_name='hardfilterresult',
            name='min_herd_size_met',
            field=models.BooleanField(default=False, verbose_name='Мин. поголовье'),
        ),
        migrations.AddField(
            model_name='hardfilterresult',
            name='no_duplicate_application',
            field=models.BooleanField(default=False, verbose_name='Нет дубликатов'),
        ),
        migrations.AddField(
            model_name='hardfilterresult',
            name='subsidy_amount_valid',
            field=models.BooleanField(default=False, verbose_name='Лимит суммы'),
        ),
        migrations.AddField(
            model_name='score',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, verbose_name='SHAP-объяснение'),
        ),
        migrations.CreateModel(
            name='ApplicationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField(default=1, verbose_name='День начала')),
                ('start_month', models.IntegerField(default=1, verbose_name='Месяц начала')),
                ('end_day', models.IntegerField(default=31, verbose_name='День окончания')),
                ('end_month', models.IntegerField(default=12, verbose_name='Месяц окончания')),
                ('is_year_round', models.BooleanField(default=True, verbose_name='Круглогодичный приём')),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='scoring.subsidydirection')),
            ],
            options={
                'verbose_name': 'Срок приёма заявок',
                'verbose_name_plural': 'Сроки приёма заявок',
            },
        ),
    ]
