# Generated by Django 5.1.6 on 2026-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submitted', 'Заявка принята'), ('info', 'Информирование'), ('hard_filter_fail', 'Проверки не пройдены'), ('scored', 'Скоринг завершён'), ('approved', 'Заявка одобрена'), ('rejected', 'Заявка отклонена'), ('waiting_list', 'Лист ожидания'), ('payment_initiated', 'Платёж инициирован'), ('paid', 'Выплата произведена'), ('review', 'Доп. проверка')], max_length=30, verbose_name='Тип'),
        ),
    ]
