# Generated by Django 5.1.15 on 2026-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_info_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfilterresult',
            name='mortality_within_norm',
            field=models.BooleanField(default=False, verbose_name='Падёж в норме'),
        ),
        migrations.AddField(
            model_name='hardfilterresult',
            name='pasture_load_valid',
            field=models.BooleanField(default=False, verbose_name='Нагрузка на пастбище'),
        ),
        migrations.AddField(
            model_name='hardfilterresult',
            name='pedigree_valid',
            field=models.BooleanField(default=False, verbose_name='Племенное свидетельство'),
        ),
    ]
