# Generated by Django 5.1.15 on 2026-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_add_regulatory_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merit_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='Разбивка Merit Score'),
        ),
        migrations.AddField(
            model_name='payment',
            name='merit_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Приоритет выплаты: 30% масштаб + 25% финансы + 25% история + 20% направление', max_digits=5, verbose_name='Merit Score'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выпла��ен'),
        ),
    ]
