# Generated by Django 5.1.6 on 2026-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin_bin', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИИН/БИН')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('entity_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('cooperative', 'С/х кооператив (СПК)')], max_length=20, verbose_name='Тип')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('district', models.CharField(max_length=200, verbose_name='Район')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('risk_profile', models.CharField(choices=[('clean', 'Чистый (70%)'), ('minor_issues', 'Мелкие проблемы (15%)'), ('risky', 'Рисковый (10%)'), ('fraudulent', 'Подозрительный (5%)')], default='clean', max_length=20, verbose_name='Профиль риска')),
                ('giss_data', models.JSONField(default=dict, verbose_name='ГИСС')),
                ('ias_rszh_data', models.JSONField(default=dict, verbose_name='ИАС РСЖ')),
                ('easu_data', models.JSONField(default=dict, verbose_name='ЕАСУ')),
                ('is_iszh_data', models.JSONField(default=dict, verbose_name='ИС ИСЖ')),
                ('is_esf_data', models.JSONField(default=dict, verbose_name='ИС ЭСФ')),
                ('egkn_data', models.JSONField(default=dict, verbose_name='ЕГКН')),
                ('treasury_data', models.JSONField(default=dict, verbose_name='Казначейство')),
                ('source_row', models.IntegerField(blank=True, null=True, verbose_name='Строка Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Эмулированная сущность',
                'verbose_name_plural': 'Эмулированные сущности',
                'ordering': ['name'],
            },
        ),
    ]
