# Generated by Django 5.1.6 on 2026-03-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_tag', models.CharField(db_index=True, max_length=50, verbose_name='Бирка животного')),
                ('rfid_tag', models.CharField(max_length=100, verbose_name='RFID-метка')),
                ('last_scan_date', models.DateTimeField(verbose_name='Последнее считывание')),
                ('scan_location', models.CharField(max_length=200, verbose_name='Место считывания')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна — давно не считывалась'), ('missing', 'Не найдена')], default='active', max_length=20, verbose_name='Статус')),
                ('scan_count_30d', models.IntegerField(default=0, verbose_name='Считываний за 30 дней')),
                ('animal_type', models.CharField(blank=True, max_length=50, verbose_name='Вид животного')),
                ('reader_type', models.CharField(blank=True, max_length=50, verbose_name='Тип считывателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_records', to='emulator.emulatedentity')),
            ],
            options={
                'verbose_name': 'RFID-мониторинг',
                'verbose_name_plural': 'RFID-мониторинг',
                'ordering': ['-last_scan_date'],
                'unique_together': {('entity', 'animal_tag')},
            },
        ),
    ]
