from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('applications/', views.application_list, name='application_list'),
    path('applications/new/', views.application_create, name='application_create'),
    path('applications/draft/', views.application_save_draft, name='application_save_draft'),
    path('applications/<int:pk>/', views.application_detail, name='application_detail'),
    path('applications/<int:pk>/success/', views.application_success, name='application_success'),
    path('scoring-methodology/', views.scoring_methodology, name='scoring_methodology'),
    path('applications/<int:pk>/decide/', views.application_decide, name='application_decide'),
    path('applications/<int:pk>/verify/', views.specialist_verify, name='specialist_verify'),
    path('applications/<int:pk>/payment/', views.payment_action, name='payment_action'),
    path('payment-queue/', views.payment_queue, name='payment_queue'),
    path('applications/<int:pk>/pdf/', views.export_application_pdf, name='application_pdf'),
    path('scoring/', views.scoring_ranking, name='scoring_ranking'),
    path('analytics/', views.analytics, name='analytics'),
    path('commission/', views.commission, name='commission'),
    path('commission/batch/', views.batch_decide, name='batch_decide'),
    path('emulator/', views.emulator_panel, name='emulator_panel'),
    path('emulator/<int:pk>/', views.entity_detail, name='entity_detail'),
    path('emulator/<int:pk>/edit/', views.entity_edit, name='entity_edit'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:pk>/read/', views.notification_read, name='notification_read'),
    path('api/entity-data/<str:iin_bin>/', views.api_entity_data, name='api_entity_data'),
    path('api/rfid-status/<str:iin_bin>/', views.api_rfid_status, name='api_rfid_status'),
    path('api/save-land-polygons/', views.api_save_land_polygons, name='api_save_land_polygons'),
    path('rfid-dashboard/', views.rfid_dashboard, name='rfid_dashboard'),
    path('model-info/', views.model_info_view, name='model_info'),
    path('api/form-progress/', views.api_form_progress, name='api_form_progress'),
    path('api/check-duplicate/', views.api_check_duplicate, name='api_check_duplicate'),
    path('api/check-duplicates-bulk/', views.api_check_duplicates_bulk, name='api_check_duplicates_bulk'),
    path('my-farm/', views.farmer_dashboard, name='farmer_dashboard'),
    path('my-analytics/', views.farmer_analytics, name='farmer_analytics'),
    path('audit-log/', views.audit_log_view, name='audit_log'),
]
